# Configuración del evaluador - Sección 4
# Ejecutar: python evaluador.py config.ini

csv_file = ./metrics.csv
inPath = ./IN/
threshold = 500
outPath1 = ./OUT_modelo1/
outPath2 = ./OUT_modelo2/
outPath3 = ./OUT_modelo3/
model1 = Salud/Salud.py
model2 = SaludCG/SaludCG.py
model3 = SaludChallenger/SaludChallenger.py
